#!/bin/bash

if [ -z "$1" ]; then
    echo "Please provide a commit message"
    exit -1
fi


gitbranch=$(git branch --show-current)

if [[ "$gitbranch" == "main" ]]
then
    echo "deploying to published track"
    mike deploy published
else
    echo "deploying to $gitbranch track"
    mike deploy $gitbranch
fi

git add .
git commit -m "$1"
git push
git checkout gh-pages
git push
git checkout $gitbranch
