site_name: Het Wetboek der Idioten
extra_css:
  - css/style.css
extra_js:
  - js/index.js
theme:
  name: material
  prev_next_buttons_location: none
  features:
    - navigation.top
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: black
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.top
plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'Wetboek-der-Idioten/index.md'
draf_docs: |
  drafts/
  _unpublished.md
hooks:
  - hooks.py

extra:
  version:
    provider: mike